package com.acclimate.payne.simpletestapp.alerts;

import com.acclimate.payne.simpletestapp.user.User;

import java.io.Serializable;
import java.util.List;

import lombok.Getter;
import lombok.Setter;

import static com.acclimate.payne.simpletestapp.photo.PhotoUtils.BASE_PATH_TO_PHOTO;

@Getter @Setter
public class UserAlert extends BasicAlert implements Serializable {

    public static final String BASE_CERTITUDE = "inconnue";

    private List<String>    plusOneUsers;       // vide par défaut, par l'app
    private List<String>    minusOneUsers;      // vide par défaut, par l'app
    private String          photoPath;          // TODO : comment faire ?
    private int             score;              // défaut 0, par l'app
    private User user;

    // // DONT REMOVE ! BUG with three letter getter / setter auto generated by Lombock and seen by Jackson
    // public void setuId(String uId){
    //     this.uId = uId;
    // }
//
    // public String getuId(){
    //     return this.uId;
    // }

    public UserAlert(){}

    @Override
    public void initType(){

        if (type != null && enumType == null){

            switch (type) {

                case "Eau":
                    enumType = AlertTypes.USER_EAU;
                    break;
                case "Feu":
                    enumType = AlertTypes.USER_FEU;
                    break;
                case "Terrain": case "Seisme":
                    enumType = AlertTypes.USER_TERRAIN;
                    break;
                case "Météo": case "Meteo" :
                default: enumType = AlertTypes.USER_METEO; break;
            }
        }
    }

    public static UserAlert emptyAlert(){
        UserAlert res = new UserAlert();
        res.setNom("Titre de l'alerte");
        res.setDescription("Description de l'alerte");
        res.setSousCategorie("Sous-catégorie");
        res.setScore(0);
        res.setType("Eau");
        res.setEnumType(AlertTypes.USER_EAU);
        return res;
    }

    public String initPhotoPath(){
        this.photoPath = String.format(BASE_PATH_TO_PHOTO, user.getUserName()) +"%s.png";
        return photoPath;
    }

}
